# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# 프로토 버퍼 메시지 정의 빌드 

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\x12\x0f\x63om.terry.proto\"2\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\tb\x06proto3')

# DESCRIPTOR 객체에서 메시지 및 열거형 기술서를 빌드하고, 이러한 기술서를 globals()로 전달하여 전역 범위에 정의될 수 있도록 합니다.
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=34
  _PERSON._serialized_end=84
# @@protoc_insertion_point(module_scope)
# 프로토콜 버퍼 컴파일러가 생성된 코드를 삽입할 수 있는 위치를 나타내기 위한 protoc 삽입 지점 주석
